separator: '|'
arpa_model: 'models_and_dicts/arpa.fst'
path_to_dict: 'models_and_dicts'
logs_dir: ''
pipeline: ['yo_replacer', 'accentor_spacy', 'accentor_static']
#  pipeline: ['yo_replacer', 'accentor_spacy', 'accentor_static', 'arpa_phonemizer']